const fs = require('fs');
const path = require('path');

const tsv = `pythagoras	Pythagoras	https://en.wikipedia.org/wiki/Pythagoras	https://upload.wikimedia.org/wikipedia/commons/1/1a/Kapitolinischer_Pythagoras_adjusted.jpg	570 – 495 BCE	-570	-495	Pythagoras of Samos was an ancient Ionian Greek philosopher and the eponymous founder of Pythagoreanism
alexander-the-great	Alexander the Great	https://wikipedia.org/wiki/Alexander_the_Great	https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/AlexandreLouvre.jpg/340px-AlexandreLouvre.jpg	20/21 July 356 BCE – 10/11 June 323 BCE	-356	-323	A king of the ancient Greek kingdom of Macedon and a member of the Argead dynasty. He was born in Pella in 356 BCE and succeeded his father Philip II to the throne at the age of 20. He spent most of his ruling years on an unprecedented military campaign through Asia and northeast Africa, and by the age of thirty he had created one of the largest empires of the ancient world, stretching from Greece to northwestern India. He was undefeated in battle and is widely considered one of history's most successful military commanders.
caesar	Caesar	https://en.wikipedia.org/wiki/Julius_Caesar	https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Retrato_de_Julio_C%C3%A9sar_%2826724093101%29.jpg/440px-Retrato_de_Julio_C%C3%A9sar_%2826724093101%29.jpg	12 or 13 July 100 BCE – 15 March 44 BCE	-100	-44	Roman politician, military general, and historian who played a critical role in the events that led to the demise of the Roman Republic and the rise of the Roman Empire
epicurus	Epicurus	https://en.wikipedia.org/wiki/Epicurus	https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Epikouros_BM_1843.jpg/440px-Epikouros_BM_1843.jpg	341 - 270 BCE	-341	-270	Epicurus was an ancient Greek philosopher and sage who founded Epicureanism, a highly influential school of philosophy.
herodotus	Herodotus	https://en.wikipedia.org/wiki/Herodotus	https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Marble_bust_of_Herodotos_MET_DT11742.jpg/440px-Marble_bust_of_Herodotos_MET_DT11742.jpg	484 - 425 BCE	-484	-425	Herodotus was an ancient Greek historian who was born in Halicarnassus in the Persian Empire. He is known for having written the book The Histories, a detailed record of his "inquiry" on the origins of the Greco-Persian Wars
aristotle	Aristotle	https://en.wikipedia.org/wiki/Aristotle	https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Aristotle_Altemps_Inv8575.jpg/440px-Aristotle_Altemps_Inv8575.jpg	384 - 322 BCE	-384	-322	Greek philosopher and polymath during the Classical period in Ancient Greece. He was the founder of the Lyceum and the Peripatetic school of philosophy and Aristotelian tradition.
cicero	Cicero	https://en.wikipedia.org/wiki/Cicero	https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Bust_of_Cicero_%281st-cent._BC%29_-_Palazzo_Nuovo_-_Musei_Capitolini_-_Rome_2016.jpg/440px-Bust_of_Cicero_%281st-cent._BC%29_-_Palazzo_Nuovo_-_Musei_Capitolini_-_Rome_2016.jpg	106 - 43 BCE	-106	-43	Roman statesman, orator, lawyer and philosopher, who served as consul in the year 63 BC. He came from a wealthy municipal family of the Roman equestrian order, and is considered one of Rome's greatest orators and prose stylists.
pericles	Pericles	https://en.wikipedia.org/wiki/Pericles	https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Pericles_Pio-Clementino_Inv269_n2.jpg/440px-Pericles_Pio-Clementino_Inv269_n2.jpg	495 - 429 BCE	-495	-429	Pericles was a prominent and influential Greek statesman, orator and general of Athens during its golden age – specifically the time between the Persian and Peloponnesian wars. Pericles also fostered Athenian democracy.
hippocrates	Hippocrates	https://en.wikipedia.org/wiki/Hippocrates	https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Hippocrates.jpg/440px-Hippocrates.jpg	460 - 370 BCE	-460	-370	Hippocrates of Kos, also known as Hippocrates II, was a Greek physician of the Age of Pericles (Classical Greece), who is considered one of the most outstanding figures in the history of medicine.
archimedes	Archimedes	https://en.wikipedia.org/wiki/Archimedes	https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Domenico-Fetti_Archimedes_1620.jpg/440px-Domenico-Fetti_Archimedes_1620.jpg	287 - 212 BCE	-287	-212	Greek mathematician, physicist, engineer, inventor, and astronomer. Although few details of his life are known, he is regarded as one of the leading scientists in classical antiquity. Generally considered the greatest mathematician of antiquity and one of the greatest of all time.
euclid	Euclid	https://en.wikipedia.org/wiki/Euclid	https://upload.wikimedia.org/wikipedia/commons/3/30/Euklid-von-Alexandria_1.jpg	~ 350 - 250 BCE	-350	-250	Euclid, sometimes called Euclid of Alexandria to distinguish him from Euclid of Megara, was a Greek mathematician, often referred to as the "founder of geometry" or the "father of geometry". He was active in Alexandria during the reign of Ptolemy I.
socrates	Socrates	https://en.wikipedia.org/wiki/Socrates	https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Socrates_Louvre.jpg/440px-Socrates_Louvre.jpg	470 - 399 BCE	-470	-399	Socrates was a classical Greek (Athenian) philosopher credited as one of the founders of Western philosophy, and as being the first moral philosopher of the Western ethical tradition of thought.
plato	Plato	https://en.wikipedia.org/wiki/Plato	https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Plato_Silanion_Musei_Capitolini_MC1377.jpg/440px-Plato_Silanion_Musei_Capitolini_MC1377.jpg	424/423 - 348/347 BCE	-424	-348	Plato was an Athenian philosopher during the Classical period in Ancient Greece, founder of the Platonist school of thought, and the Academy, the first institution of higher learning in the Western world.
heraclitus	Heraclitus	https://en.wikipedia.org/wiki/Heraclitus	https://upload.wikimedia.org/wikipedia/en/thumb/8/86/Heraklit.jpg/440px-Heraklit.jpg	535 - 375 BCE	-535	-375	Heraclitus of Ephesus son of Bloson, was a pre-Socratic Ionian Greek philosopher, and a native of the city of Ephesus, in modern-day Turkey and then part of the Persian Empire.
democritus	Democritus	https://en.wikipedia.org/wiki/Democritus	https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Democritus2.jpg/440px-Democritus2.jpg	460 - 370 BCE	-460	-370	Democritus was an Ancient Greek pre-Socratic philosopher primarily remembered today for his formulation of an atomic theory of the universe
water-wheel	Water wheel	https://en.wikipedia.org/wiki/Water_wheel#History	https://upload.wikimedia.org/wikipedia/commons/d/d4/Berry_Schools%27_Old_Mill%2C_Floyd_County%2C_Georgia.jpg	~ 400 - 300 BCE	-350	-350	It is not clear from the available historic texts and archaeology whether the watermill originates in Egypt, Persia, India, Greece, or regions in-between; usage within just a few decades of each other's cultures in the 4th to 3rd centuries BCE is documented over a large swath of Eurasia.
catapult	Catapult	https://en.wikipedia.org/wiki/Catapult	https://upload.wikimedia.org/wikipedia/commons/c/cb/Replica_catapult.jpg	~ 4th century BCE	-380	-380	The earliest catapults date to at least the 4th century BC with the advent of the mangonel in ancient China, a type of traction trebuchet and catapult.[3][4] Early uses were also attributed to Ajatashatru of Magadha in his war against the Licchavis.[5] Early Greek catapults emerged around the 1st century BC.
christianity	Christianity	https://en.wikipedia.org/wiki/Christianity	https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Christian_cross.svg/150px-Christian_cross.svg.png	1st century	0	0	Christianity is an Abrahamic religion based on the life and teachings of Jesus of Nazareth, as described in the New Testament.
marcus-aurelius	Marcus Aurelius	https://en.wikipedia.org/wiki/Marcus_Aurelius	https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/L%27Image_et_le_Pouvoir_-_Buste_cuirass%C3%A9_de_Marc_Aur%C3%A8le_ag%C3%A9_-_3.jpg/440px-L%27Image_et_le_Pouvoir_-_Buste_cuirass%C3%A9_de_Marc_Aur%C3%A8le_ag%C3%A9_-_3.jpg	26 Apri 121 - 17 March 180	121	180	Marcus Aurelius was Roman emperor from 161 to 180 and a Stoic philosopher. He was the last of the rulers known as the Five Good Emperors, and the last emperor of the Pax Romana, an age of relative peace and stability for the Roman Empire. He served as Roman consul in 140, 145, and 161.
constantine	Constantine the Great	https://en.wikipedia.org/wiki/Constantine_the_Great	https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Rome-Capitole-StatueConstantin.jpg/440px-Rome-Capitole-StatueConstantin.jpg	274 - 337	274	337	Constantine I was also known as Constantine the Great, and he happened to be one of those emperors who did true justice to their names. The vast Roman Empire had been divided up between many different rulers by the third century AD.
hipatia	Hipatia	https://en.wikipedia.org/wiki/Hypatia	https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Hypatia_portrait.png/520px-Hypatia_portrait.png	350/370 - 415	370	415	Hypatia was a Hellenistic Neoplatonist philosopher, astronomer, and mathematician, who lived in Alexandria, Egypt, then part of the Eastern Roman Empire. She was a prominent thinker of the Neoplatonic school in Alexandria where she taught philosophy and astronomy. She is the first female mathematician whose life is reasonably well recorded.
byzantine-empire	Byzantine Empire	https://en.wikipedia.org/wiki/Byzantine_Empire	https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Simple_Labarum.svg/160px-Simple_Labarum.svg.png	395 - 1453	395	1453	The Byzantine Empire, also referred to as the Eastern Roman Empire or Byzantium, was the continuation of the Roman Empire in its eastern provinces during Late Antiquity and the Middle Ages, when its capital city was Constantinople (modern Istanbul, formerly Byzantium).
dark-ages	Dark Ages	https://en.wikipedia.org/wiki/Dark_Ages_(historiography)	https://upload.wikimedia.org/wikipedia/commons/8/8f/Petrarch_by_Bargilla.jpg	from the 5th to the 15th century	500	1500	The "Dark Ages" is a historical periodization traditionally referring to the Middle Ages
islam	Islam	https://en.wikipedia.org/wiki/Islam	https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Allah3.svg/220px-Allah3.svg.png	~700	700	700	Islam is an Abrahamic monotheistic religion teaching that there is only one God (Arabic: Allah), and that Muhammad is the messenger of God.
gunpowder	Gunpowder	https://en.wikipedia.org/wiki/Gunpowder#History_of_gunpowder	https://upload.wikimedia.org/wikipedia/commons/9/9c/Black_Powder_Close_Up.jpg	904	904	904	Gunpowder was invented in 9th-century China as one of the Four Great Inventions, and spread throughout most parts of Eurasia by the end of the 13th century.[3] Originally developed by the Taoists for medicinal purposes, gunpowder was first used for warfare about 904 AD.
omar-khayyam	Omar Khayyam	https://wikipedia.org/wiki/Omar_Khayyam	https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Omar_Khayyam2.JPG/440px-Omar_Khayyam2.JPG	18 May 1048 – 4 December 1131	1048	1131	Persian mathematician, astronomer, and poet
crusades	Crusades	https://en.wikipedia.org/wiki/Crusades	https://upload.wikimedia.org/wikipedia/commons/f/f5/Combat_deuxi%C3%A8me_croisade.jpg	1095 – 1492	1095	1492	The Crusades were a series of religious wars sanctioned by the Latin Church in the medieval period.
firearms	Firearms	https://en.wikipedia.org/wiki/Firearm#History	https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Jacob_de_Gheyn_-_Wapenhandelinge_4.jpg/440px-Jacob_de_Gheyn_-_Wapenhandelinge_4.jpg	around 1250	1250	1250	first way use of powder
dante-alighieri	Dante Alighieri	https://wikipedia.org/wiki/Dante_Alighieri	https://upload.wikimedia.org/wikipedia/commons/6/6f/Portrait_de_Dante.jpg	1265 – 1321	1265	1321	Italian poet during the Late Middle Ages. His Divine Comedy, originally called "Comedìa" and later christened Divina by Giovanni Boccaccio, is widely considered the most important poem of the Middle Ages and the greatest literary work in the Italian language.
renaissance	Renaissance	https://wikipedia.org/wiki/Renaissance	https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg/500px-%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg	~ 14th – 17th centuries	1300	1600	a period in European history, covering the span between the 14th and 17th centuries and marking the transition from the Middle Ages to modernity. The traditional view focuses more on the early modern aspects of the Renaissance and argues that it was a break from the past, but many historians today focus more on its medieval aspects and argue that it was an extension of the middle ages
printing-press	Printing press	https://wikipedia.org/wiki/Printing_press	https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Chodowiecki_Basedow_Tafel_21_c_Z.jpg/622px-Chodowiecki_Basedow_Tafel_21_c_Z.jpg	1440	1440	1440	Johannes Gutenberg, a goldsmith by profession, developed, circa 1439, a printing system by adapting existing technologies to printing purposes, as well as making inventions of his own. His newly devised hand mould made possible the precise and rapid creation of metal movable type in large quantities. Movable type had been hitherto unknown in Europe. In Europe, the two inventions, the hand mould and the printing press, together drastically reduced the cost of printing books and other documents, particularly in short print runs.
leonardo-da-vinci	Leonardo da Vinci	https://wikipedia.org/wiki/Leonardo_da_Vinci	https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Da_Vinci_Vitruve_Luc_Viatour_%28cropped%29.jpg/440px-Da_Vinci_Vitruve_Luc_Viatour_%28cropped%29.jpg	15 April 1452 – 2 May 1519	1452	1519	Italian polymath of the Renaissance whose areas of interest included invention, drawing, painting, sculpting, architecture, science, music, mathematics, engineering, literature, anatomy, geology, astronomy, botany, writing, history, and cartography
nikola-copernicus	Nikola Copernicus	https://en.wikipedia.org/wiki/Nicolaus_Copernicus	https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Nikolaus_Kopernikus.jpg/440px-Nikolaus_Kopernikus.jpg	19 February 1473 – 24 May 1543	1473	1543	Nicolaus Copernicus was a Renaissance-era mathematician and astronomer who formulated a model of the universe that placed the Sun rather than the Earth at the center of the universe, in all likelihood independently of Aristarchus of Samos, who had formulated such a model some eighteen centuries earlier.
discovery-of-america	Discovery of America	https://en.wikipedia.org/wiki/Voyages_of_Christopher_Columbus#First_voyage	https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Landing_of_Columbus_%282%29.jpg/440px-Landing_of_Columbus_%282%29.jpg	October 12, 1492	1492	1492	Europe discovers America
islamic-golden-age	Islamic Golden Age	https://en.wikipedia.org/wiki/Islamic_Golden_Age	https://upload.wikimedia.org/wikipedia/commons/2/2c/Maqamat_hariri.jpg	~ 8th .. 14th century	700	1300	a period of cultural, economic and scientific flourishing in the history of Islam, traditionally dated from the 8th century to the 14th century.
glasses	Eye-glasses	https://en.wikipedia.org/wiki/Glasses#History	https://upload.wikimedia.org/wikipedia/commons/c/cf/Conrad_von_Soest%2C_%27Brillenapostel%27_%281403%29.jpg	~1290	1290	1290	The first eyeglasses were made in Northern Italy, most likely in Pisa, by about 1290
windmill	Windmills become popular	https://en.wikipedia.org/wiki/Windmill	https://upload.wikimedia.org/wikipedia/commons/e/ec/Windmill_at_Watermill%2C_Southampton_NY_20180914_080131.jpg	~14th century	1300	1300	Windmills were used throughout the high medieval and early modern periods; the horizontal or panemone windmill first appeared in Greater Iran during the 9th century, the vertical windmill in northwestern Europe in the 12th century.
on-the-fabric-of-the-human-body	on the fabric of the human body	https://en.wikipedia.org/wiki/De_humani_corporis_fabrica	https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Vesalius_Fabrica_p163.jpg/340px-Vesalius_Fabrica_p163.jpg	1543	1543	1543	It was a major advance in the history of anatomy over the long-dominant work of Galen, and presented itself as such
scientific-revolution	Scientific Revolution	https://wikipedia.org/wiki/Scientific_Revolution	https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/CMB_Timeline300_no_WMAP.jpg/520px-CMB_Timeline300_no_WMAP.jpg	~ 1543	1543	1543	The Scientific Revolution was a series of events that marked the emergence of modern science during the early modern period, when developments in mathematics, physics, astronomy, biology (including human anatomy) and chemistry transformed the views of society about nature
giordano-bruno	Giordano Bruno	https://wikipedia.org/wiki/Giordano_Bruno	https://upload.wikimedia.org/wikipedia/commons/1/15/Giordano_Bruno.jpg	1548 – 17 February 1600	1548	1600	Italian Dominican friar, philosopher, mathematician, poet, cosmological theorist, and Hermetic occultist
galileo	Galileo	https://en.wikipedia.org/wiki/Galileo_Galilei	https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Justus_Sustermans_-_Portrait_of_Galileo_Galilei%2C_1636.jpg/440px-Justus_Sustermans_-_Portrait_of_Galileo_Galilei%2C_1636.jpg	15 February 1564 – 8 January 1642	1564	1642	Galileo Galilei was an Italian astronomer, physicist and engineer, sometimes described as a polymath.
william-shakespeare	William Shakespeare	https://wikipedia.org/wiki/William_Shakespeare	https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Shakespeare.jpg/375px-Shakespeare.jpg	bapt. 26 April 1564 – 23 April 1616	1564	1616	English poet, playwright and actor, widely regarded as the greatest writer in the English language and the world's greatest dramatist
isaac-newton	Isaac Newton	https://wikipedia.org/wiki/Isaac_Newton	https://upload.wikimedia.org/wikipedia/commons/3/39/GodfreyKneller-IsaacNewton-1689.jpg	25 December 1642 – 20 March 1726/27	1642	1727	English mathematician, physicist, astronomer, theologian, and author (described in his own day as a "natural philosopher") who is widely recognised as one of the most influential scientists of all time, and a key figure in the scientific revolution
capitalism	Capitalism	https://en.wikipedia.org/wiki/Capitalism	https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/McKinley_Prosperity.jpg/340px-McKinley_Prosperity.jpg	?	1700	1700	Capitalism is an economic system based on the private ownership of the means of production and their operation for profit
steam-engine	Steam engine	https://wikipedia.org/wiki/Steam_engine	https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/JamesWattEngine.jpg/640px-JamesWattEngine.jpg	1712	1712	1712	
automobile	Automobile	https://en.wikipedia.org/wiki/History_of_the_automobile	https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Ford_Model_T_and_VW_type_11_Luxus%2C_Technisches_Museum_Wien%2C_Juni_2009.jpg/600px-Ford_Model_T_and_VW_type_11_Luxus%2C_Technisches_Museum_Wien%2C_Juni_2009.jpg	1769	1769	1769	First steam-powered automobile capable of human transportation was built by Nicolas-Joseph Cugnot
napoleon	Napoléon Bonaparte	https://wikipedia.org/wiki/Napoleon	https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Jacques-Louis_David_-_The_Emperor_Napoleon_in_His_Study_at_the_Tuileries_-_Google_Art_Project.jpg/288px-Jacques-Louis_David_-_The_Emperor_Napoleon_in_His_Study_at_the_Tuileries_-_Google_Art_Project.jpg	15 August 1769 – 5 May 1821	1769	1821	French statesman and military leader who rose to prominence during the French Revolution and led several successful campaigns during the French Revolutionary Wars
united-states	USA	https://wikipedia.org/wiki/United_States	https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg	July 4, 1776	1776	1776	
french-revolution	French Revolution	https://en.wikipedia.org/wiki/French_Revolution	https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Anonymous_-_Prise_de_la_Bastille.jpg/480px-Anonymous_-_Prise_de_la_Bastille.jpg	5 May 1789 – 9 November 1799	1789	1799	The French Revolution was a period of far-reaching social and political upheaval in France and its colonies beginning in 1789.
michael-faraday	Michael Faraday	https://wikipedia.org/wiki/Michael_Faraday	https://upload.wikimedia.org/wikipedia/commons/8/88/M_Faraday_Th_Phillips_oil_1842.jpg	22 September 1791 – 25 August 1867	1791	1867	English scientist who contributed to the study of electromagnetism and electrochemistry. His main discoveries include the principles underlying electromagnetic induction, diamagnetism and electrolysis
steam-locomotive	Steam locomotive	https://wikipedia.org/wiki/Steam_locomotive	https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/California_Western_Railroad_Locomotive_45.jpg/440px-California_Western_Railroad_Locomotive_45.jpg	1802	1802	1802	
charles-darwin	Charles Darwin	https://wikipedia.org/wiki/Charles_Darwin	https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Charles_Robert_Darwin_by_John_Collier.jpg/440px-Charles_Robert_Darwin_by_John_Collier.jpg	12 February 1809 – 19 April 1882	1809	1882	English naturalist, geologist and biologist, best known for his contributions to the science of evolution. His proposition that all species of life have descended over time from common ancestors is now widely accepted, and considered a foundational concept in science. In a joint publication with Alfred Russel Wallace, he introduced his scientific theory that this branching pattern of evolution resulted from a process that he called natural selection, in which the struggle for existence has a similar effect to the artificial selection involved in selective breeding.
view-from-the-window-at-le-gras	First photo	https://wikipedia.org/wiki/View_from_the_Window_at_Le_Gras	https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/LEI0440_Leica_IIIf_chrom_-_Sn._580566_1951-52-M39_Blitzsynchron_front_view-6531_hf-.jpg/440px-LEI0440_Leica_IIIf_chrom_-_Sn._580566_1951-52-M39_Blitzsynchron_front_view-6531_hf-.jpg	~ 1826	1826	1826	Nicéphore Niépce — French inventor, usually credited as the inventor of photography and a pioneer in that field
metropolitan-railway	Metropolitan Railway	https://wikipedia.org/wiki/Metropolitan_Railway	https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Metropolitan_Underground_Railway_stations.jpg/440px-Metropolitan_Underground_Railway_stations.jpg	1863	1863	1863	The Metropolitan Railway was a passenger and goods railway that served London from 1863 to 1933. It opened to the public on 10 January 1863 with gas-lit wooden carriages hauled by steam locomotives, the world's first passenger-carrying designated underground railway.
albert-einstein	Albert Einstein	https://wikipedia.org/wiki/Albert_Einstein	https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Einstein_1921_by_F_Schmutzer_-_restoration.jpg/440px-Einstein_1921_by_F_Schmutzer_-_restoration.jpg	14 March 1879 – 18 April 1955	1879	1955	Theoretical physicist who developed the theory of relativity. E = mc2
incandescent-light-bulb	Light bulb	https://wikipedia.org/wiki/Incandescent_light_bulb	https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Livermore_Centennial_Light_Bulb.jpg/266px-Livermore_Centennial_Light_Bulb.jpg	Around 1880s	1880	1880	
radio	Radio	https://en.wikipedia.org/wiki/Invention_of_radio	https://upload.wikimedia.org/wikipedia/commons/1/12/FFU_trx_Stiff_1904.JPG	around 1890s	1890	1890	
world-war-i	World War I	https://wikipedia.org/wiki/World_War_I	https://upload.wikimedia.org/wikipedia/commons/2/20/WWImontage.jpg	28 July 1914 – 11 November 1918	1914	1918	Also known as the First World War or the Great War, was a global war originating in Europe that lasted from 28 July 1914 to 11 November 1918. Contemporaneously described as "the war to end all wars", it led to the mobilisation of more than 70 million military personnel, including 60 million Europeans, making it one of the largest wars in history. It is also one of the deadliest conflicts in history, with an estimated nine million combatants and seven million civilian deaths as a direct result of the war, while resulting genocides and the 1918 influenza pandemic caused another 50 to 100 million deaths worldwide.
soviet-union	USSR	https://wikipedia.org/wiki/Soviet_Union	https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_the_Soviet_Union.svg	1922 – 1991	1922	1991	
world-war-ii	World War II	https://wikipedia.org/wiki/World_War_II	https://upload.wikimedia.org/wikipedia/commons/5/54/Infobox_collage_for_WWII.PNG	1 September 1939 – 2 September 1945	1939	1945	also known as the Second World War, was a global war that lasted from 1939 to 1945. The vast majority of the world's countries—including all the great powers—eventually formed two opposing military alliances: the Allies and the Axis. A state of total war emerged, directly involving more than 100 million people from over 30 countries. The major participants threw their entire economic, industrial, and scientific capabilities behind the war effort, blurring the distinction between civilian and military resources. World War II was the deadliest conflict in human history, marked by 50 to 85 million fatalities, most of whom were civilians in the Soviet Union and China. It included massacres, the genocide of the Holocaust, strategic bombing, premeditated death from starvation and disease, and the only use of nuclear weapons in war
modern-computer	Modern Computer	https://en.wikipedia.org/wiki/Colossus_computer	https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Colossus.jpg/600px-Colossus.jpg	1943–1945	1943	1945	Modern computers
nuclear-weapons	Nuclear weapons	https://en.wikipedia.org/wiki/Nuclear_weapon	https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Nagasakibomb.jpg/440px-Nagasakibomb.jpg	August 6, 9 1945	1945	1945	A nuclear weapon ( also called an atom bomb, nuke, atomic bomb, nuclear warhead, A-bomb, or nuclear bomb) is an explosive device that derives its destructive force from nuclear reactions.
public-tv	Public TV	https://en.wikipedia.org/wiki/History_of_television	https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/SMPTE_Color_Bars.svg/440px-SMPTE_Color_Bars.svg.png	around 1950s	1950	1950	Broadcasted television
first-human-in-space	First human in space	https://en.wikipedia.org/wiki/Yuri_Gagarin	https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Yuri-Gagarin-1961-Helsinki-crop.jpg/440px-Yuri-Gagarin-1961-Helsinki-crop.jpg	April 12, 1961	1961	1961	On 12 April 1961, 6:07 am UTC, the Vostok 3KA-3 (Vostok 1) spacecraft with Gagarin aboard was launched from Baikonur Cosmodrome.`;

const createMeta = (id, title, wikiUrl, imageUrl, subtitle, from, to, short) =>
`<!--
id:          ${ id }
title:       ${ title }
subtitle:    ${ subtitle }
from:        ${ from }
to:          ${ to } 
short:       ${ short }
imageUrl:    ${ imageUrl }
wikiUrl:     ${ wikiUrl}
-->
`;

tsv.split(/\n/).forEach(line => {
    const [id = '', title = '', wikiUrl = '', imageUrl = '', subtitle = '', from = '', to = '', short = '', mdContent = ''] = line.split(/\t/);
    const fileName = id || title.toLowerCase().replace(/\s/g, '-');
    const meta = createMeta(id, title, wikiUrl, imageUrl, subtitle, from, to, short);
    const content = meta + '\n\n' + (mdContent || short);
    const p = path.resolve(__dirname, `../src/data/entries/${ fileName }.md`);

    if (fs.existsSync(p)) {
        return;
    }

    // console.log(content);
    fs.writeFileSync(p, content, 'utf-8');
})